### ISSUE TITLE
三元运算符

### ISSUE THREAD

**Issue by xandery-geek** [WiseDoge/libkdtree#2]
p = coor[p->split] <= GetDimVal(p->id, p->split) ? p = p->left : p = p->right; 
应该是这样吧: p = coor[p->split] <= GetDimVal(p->id, p->split) ? p->left : p->right;
虽然那么写执行的结果是一样的，但是多了两次赋值，而且阅读代码时会让人感到困惑。

**Comment by liuslnlp** [comment]
多谢，改一下

发自我的 iPhone

在 2019年6月7日，18:05，yuanxu <notifications@github.com<mailto:notifications@github.com>> 写道：


p = coor[p->split] <= GetDimVal(p->id, p->split) ? p = p->left : p = p->right;
应该是这样吧: p = coor[p->split] <= GetDimVal(p->id, p->split) ? p->left : p->right;
虽然那么写执行的结果是一样的，但是多了两次赋值，而且阅读代码时会让人感到困惑。
